import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import type pg from 'pg';
import { createHmac } from 'node:crypto';
import { seedTeacher, testAdminPool, testAppPool } from './helpers';
import { buildTestApp, inject, TEST_JOIN_CODE_PEPPER, type NestApp } from './app';

/**
 * TST-JOIN-CODE-001 — class-code entry.
 *
 * A code is generated by the application with a CSPRNG and stored only as a
 * keyed digest, so the database never holds a working code. Resolving one
 * answers which class it is and creates nothing: no session, no membership,
 * no seat. An unknown code is indistinguishable from a malformed one.
 */

let admin: pg.Pool;
let runtime: pg.Pool;
let app: NestApp;

/** A fresh code per run: an active digest is unique, so fixtures must not repeat. */
function freshCode(): string {
  const alphabet = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  let code = '';
  for (let index = 0; index < 8; index += 1) {
    code += alphabet[Math.floor(Math.random() * alphabet.length)];
  }
  return code;
}

function digestOf(code: string): string {
  return createHmac('sha256', TEST_JOIN_CODE_PEPPER)
    .update(code.replace(/[\s-]/g, '').toUpperCase())
    .digest('hex');
}

/** Seeds a class and issues a code the same way the API does. */
async function seedClassroom(
  label: string,
  code: string,
): Promise<{ title: string; classroomId: string; tenantId: string }> {
  const teacher = await seedTeacher(admin, label);
  const title = `Класс ${label}`;
  const inserted = await admin.query(
    `INSERT INTO classrooms (tenant_id, school_id, academic_period_id, title, created_by)
     VALUES ($1, $2, $3, $4, $5) RETURNING id`,
    [teacher.tenantId, teacher.schoolId, teacher.periodId, title, teacher.teacherId],
  );
  const classroomId = inserted.rows[0].id as string;
  await admin.query(`SELECT classroom_issue_join_code($1, $2, $3)`, [
    teacher.tenantId,
    classroomId,
    digestOf(code),
  ]);
  return { title, classroomId, tenantId: teacher.tenantId };
}

async function resolve(code: unknown) {
  return inject(app, { method: 'POST', url: '/api/join-class/resolve', payload: { code } });
}

beforeAll(async () => {
  admin = testAdminPool();
  runtime = testAppPool();
  app = await buildTestApp(runtime);
});

afterAll(async () => {
  await app.close();
  await admin.end();
});

describe('class code resolution', () => {
  it('previews the class behind an active code', async () => {
    const code = freshCode();
    const classroom = await seedClassroom('code', code);
    const response = await resolve(code);
    expect(response.statusCode).toBe(200);
    expect(response.json().classroom.title).toBe(classroom.title);
    expect(typeof response.json().classroom.educatorDisplayName).toBe('string');
  });

  it('accepts a code copied with spaces, dashes and the wrong case', async () => {
    const code = freshCode();
    const classroom = await seedClassroom('normalize', code);
    const response = await resolve(` ${code.slice(0, 4).toLowerCase()}-${code.slice(4)} `);
    expect(response.statusCode).toBe(200);
    expect(response.json().classroom.title).toBe(classroom.title);
  });

  it('stores only a keyed digest, never the code itself', async () => {
    const code = freshCode();
    const classroom = await seedClassroom('digest', code);
    const stored = await admin.query(
      `SELECT lookup_digest, status, version FROM classroom_join_codes WHERE classroom_id = $1`,
      [classroom.classroomId],
    );
    expect(stored.rows[0].lookup_digest).toBe(digestOf(code));
    expect(stored.rows[0].lookup_digest).not.toContain(code);
    expect(stored.rows[0].status).toBe('active');
    expect(stored.rows[0].version).toBe(1);

    // The digest is keyed: without the pepper the same code hashes differently.
    const unkeyed = createHmac('sha256', 'another-pepper').update(code).digest('hex');
    expect(stored.rows[0].lookup_digest).not.toBe(unkeyed);
  });

  it('rotates: issuing a new code retires the old one', async () => {
    const first = freshCode();
    const second = freshCode();
    const classroom = await seedClassroom('rotate', first);
    expect((await resolve(first)).statusCode).toBe(200);

    await admin.query(`SELECT classroom_issue_join_code($1, $2, $3)`, [
      classroom.tenantId,
      classroom.classroomId,
      digestOf(second),
    ]);

    expect((await resolve(first)).statusCode).toBe(404);
    expect((await resolve(second)).statusCode).toBe(200);

    const versions = await admin.query(
      `SELECT version, status FROM classroom_join_codes WHERE classroom_id = $1 ORDER BY version`,
      [classroom.classroomId],
    );
    expect(versions.rows).toEqual([
      { version: 1, status: 'revoked' },
      { version: 2, status: 'active' },
    ]);
  });

  it('revokes: a revoked code stops resolving', async () => {
    const code = freshCode();
    const classroom = await seedClassroom('revoke', code);
    expect((await resolve(code)).statusCode).toBe(200);

    const revoked = await admin.query(`SELECT classroom_revoke_join_code($1, $2) AS n`, [
      classroom.tenantId,
      classroom.classroomId,
    ]);
    expect(revoked.rows[0].n).toBe(1);
    expect((await resolve(code)).statusCode).toBe(404);
  });

  it('creates no membership, no seat and no session', async () => {
    const code = freshCode();
    await seedClassroom('no-side-effect', code);
    const before = await admin.query(`SELECT count(*)::int AS n FROM sessions`);
    const memberships = await admin.query(`SELECT count(*)::int AS n FROM classroom_memberships`);

    const response = await resolve(code);
    expect(response.statusCode).toBe(200);
    expect(response.cookies).toHaveLength(0);

    const afterSessions = await admin.query(`SELECT count(*)::int AS n FROM sessions`);
    const afterMemberships = await admin.query(
      `SELECT count(*)::int AS n FROM classroom_memberships`,
    );
    expect(afterSessions.rows[0].n).toBe(before.rows[0].n);
    expect(afterMemberships.rows[0].n).toBe(memberships.rows[0].n);
  });

  it('answers an unknown code exactly like a malformed one', async () => {
    const unknown = await resolve('ZZZZZZZZ');
    const malformed = await resolve('!!');
    expect(unknown.statusCode).toBe(404);
    expect(malformed.statusCode).toBe(404);
    expect(malformed.json()).toEqual(unknown.json());
    expect(unknown.json().error.code).toBe('class_not_found');
  });

  it('rejects a body that carries anything but the code', async () => {
    const response = await inject(app, {
      method: 'POST',
      url: '/api/join-class/resolve',
      payload: { code: 'ABCDEFGH', tenantId: 'anything' },
    });
    expect(response.statusCode).toBe(400);
  });

  it('keeps the code table unreachable for the runtime role', async () => {
    await expect(
      runtime.query(`SELECT lookup_digest FROM classroom_join_codes`),
    ).rejects.toMatchObject({ code: '42501' });
    // The narrow function is the only way in, and it still answers.
    const code = freshCode();
    await seedClassroom('rls', code);
    expect((await resolve(code)).statusCode).toBe(200);
  });
});
