import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import type pg from 'pg';
import { createHmac } from 'node:crypto';
import { seedTeacher, testAdminPool, testAppPool } from './helpers';
import { buildTestApp, inject, TEST_JOIN_CODE_PEPPER, type NestApp } from './app';

/**
 * TST-JOIN-CODE-001 — class-code entry.
 *
 * A code is generated by the application with a CSPRNG and stored only as a
 * keyed digest, so the database never holds a working code. Resolving one
 * answers which class it is and creates nothing: no session, no membership,
 * no seat, and no classroom identifier for the browser to tamper with. What
 * comes back is a signed, short-lived intent token the server re-checks.
 */

let admin: pg.Pool;
let runtime: pg.Pool;
let app: NestApp;

/** A fresh code per run: an active digest is unique, so fixtures must not repeat. */
function freshCode(): string {
  const alphabet = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  let code = '';
  for (let index = 0; index < 8; index += 1) {
    code += alphabet[Math.floor(Math.random() * alphabet.length)];
  }
  return code;
}

function digestOf(code: string): string {
  return createHmac('sha256', TEST_JOIN_CODE_PEPPER)
    .update(code.replace(/[\s-]/g, '').toUpperCase())
    .digest('hex');
}

/** Seeds a class and issues a code the same way the application does. */
async function seedClassroom(
  label: string,
  code: string,
): Promise<{ title: string; classroomId: string; tenantId: string }> {
  const teacher = await seedTeacher(admin, label);
  const title = `Класс ${label}`;
  const inserted = await admin.query(
    `INSERT INTO classrooms (tenant_id, school_id, academic_period_id, title, created_by)
     VALUES ($1, $2, $3, $4, $5) RETURNING id`,
    [teacher.tenantId, teacher.schoolId, teacher.periodId, title, teacher.teacherId],
  );
  const classroomId = inserted.rows[0].id as string;
  await admin.query(`SELECT classroom_issue_join_code($1, $2, $3)`, [
    teacher.tenantId,
    classroomId,
    digestOf(code),
  ]);
  return { title, classroomId, tenantId: teacher.tenantId };
}

async function resolve(code: unknown) {
  return inject(app, { method: 'POST', url: '/api/join-class/resolve', payload: { code } });
}

async function describeIntent(joinIntentToken: unknown) {
  return inject(app, {
    method: 'POST',
    url: '/api/join-class/intent',
    payload: { joinIntentToken },
  });
}

/** Runs a body with the class-code secret unset or damaged. */
async function withSecret<T>(value: string | undefined, body: () => Promise<T>): Promise<T> {
  const previous = process.env['ASA_JOIN_CODE_PEPPER'];
  if (value === undefined) delete process.env['ASA_JOIN_CODE_PEPPER'];
  else process.env['ASA_JOIN_CODE_PEPPER'] = value;
  try {
    return await body();
  } finally {
    if (previous === undefined) delete process.env['ASA_JOIN_CODE_PEPPER'];
    else process.env['ASA_JOIN_CODE_PEPPER'] = previous;
  }
}

beforeAll(async () => {
  admin = testAdminPool();
  runtime = testAppPool();
  app = await buildTestApp(runtime);
});

afterAll(async () => {
  await app.close();
  await admin.end();
});

describe('class code resolution', () => {
  it('previews the class behind an active code and hands back an opaque intent', async () => {
    const code = freshCode();
    const classroom = await seedClassroom('code', code);
    const response = await resolve(code);
    expect(response.statusCode).toBe(200);

    const answer = response.json().classroom;
    expect(answer.title).toBe(classroom.title);
    expect(typeof answer.educatorDisplayName).toBe('string');
    expect(typeof answer.joinIntentToken).toBe('string');

    // The classroom identifier never reaches the browser, in any field.
    expect(JSON.stringify(answer)).not.toContain(classroom.classroomId);
    expect(answer.id).toBeUndefined();
    expect(answer.classroomId).toBeUndefined();
  });

  it('accepts a code copied with spaces, dashes and the wrong case', async () => {
    const code = freshCode();
    const classroom = await seedClassroom('normalize', code);
    const response = await resolve(` ${code.slice(0, 4).toLowerCase()}-${code.slice(4)} `);
    expect(response.statusCode).toBe(200);
    expect(response.json().classroom.title).toBe(classroom.title);
  });

  it('stores only a keyed digest, never the code itself', async () => {
    const code = freshCode();
    const classroom = await seedClassroom('digest', code);
    const stored = await admin.query(
      `SELECT lookup_digest, status, version FROM classroom_join_codes WHERE classroom_id = $1`,
      [classroom.classroomId],
    );
    expect(stored.rows[0].lookup_digest).toBe(digestOf(code));
    expect(stored.rows[0].lookup_digest).not.toContain(code);
    expect(stored.rows[0].status).toBe('active');
    expect(stored.rows[0].version).toBe(1);

    // The digest is keyed: without the pepper the same code hashes differently.
    const unkeyed = createHmac('sha256', 'another-pepper').update(code).digest('hex');
    expect(stored.rows[0].lookup_digest).not.toBe(unkeyed);
  });

  it('rotates: issuing a new code retires the old one', async () => {
    const first = freshCode();
    const second = freshCode();
    const classroom = await seedClassroom('rotate', first);
    expect((await resolve(first)).statusCode).toBe(200);

    await admin.query(`SELECT classroom_issue_join_code($1, $2, $3)`, [
      classroom.tenantId,
      classroom.classroomId,
      digestOf(second),
    ]);

    expect((await resolve(first)).statusCode).toBe(404);
    expect((await resolve(second)).statusCode).toBe(200);

    const versions = await admin.query(
      `SELECT version, status FROM classroom_join_codes WHERE classroom_id = $1 ORDER BY version`,
      [classroom.classroomId],
    );
    expect(versions.rows).toEqual([
      { version: 1, status: 'revoked' },
      { version: 2, status: 'active' },
    ]);
  });

  it('revokes: a revoked code stops resolving', async () => {
    const code = freshCode();
    const classroom = await seedClassroom('revoke', code);
    expect((await resolve(code)).statusCode).toBe(200);

    const revoked = await admin.query(`SELECT classroom_revoke_join_code($1, $2) AS n`, [
      classroom.tenantId,
      classroom.classroomId,
    ]);
    expect(revoked.rows[0].n).toBe(1);
    expect((await resolve(code)).statusCode).toBe(404);
  });

  it('creates no membership, no seat and no session', async () => {
    const code = freshCode();
    await seedClassroom('no-side-effect', code);
    const before = await admin.query(`SELECT count(*)::int AS n FROM sessions`);
    const memberships = await admin.query(`SELECT count(*)::int AS n FROM classroom_memberships`);

    const response = await resolve(code);
    expect(response.statusCode).toBe(200);
    expect(response.cookies).toHaveLength(0);

    const afterSessions = await admin.query(`SELECT count(*)::int AS n FROM sessions`);
    const afterMemberships = await admin.query(
      `SELECT count(*)::int AS n FROM classroom_memberships`,
    );
    expect(afterSessions.rows[0].n).toBe(before.rows[0].n);
    expect(afterMemberships.rows[0].n).toBe(memberships.rows[0].n);
  });

  it('answers an unknown code exactly like a malformed one', async () => {
    const unknown = await resolve('ZZZZZZZZ');
    const malformed = await resolve('!!');
    expect(unknown.statusCode).toBe(404);
    expect(malformed.statusCode).toBe(404);
    expect(malformed.json()).toEqual(unknown.json());
    expect(unknown.json().error.code).toBe('class_not_found');
  });

  it('rejects a body that carries anything but the code', async () => {
    const response = await inject(app, {
      method: 'POST',
      url: '/api/join-class/resolve',
      payload: { code: 'ABCDEFGH', tenantId: 'anything' },
    });
    expect(response.statusCode).toBe(400);
  });

  it('keeps the code table unreachable for the runtime role', async () => {
    await expect(
      runtime.query(`SELECT lookup_digest FROM classroom_join_codes`),
    ).rejects.toMatchObject({ code: '42501' });
    // The narrow function is the only way in, and it still answers.
    const code = freshCode();
    await seedClassroom('rls', code);
    expect((await resolve(code)).statusCode).toBe(200);
  });
});

describe('join intent token', () => {
  it('describes its class, and is the only thing that names it', async () => {
    const code = freshCode();
    const classroom = await seedClassroom('intent', code);
    const token = (await resolve(code)).json().classroom.joinIntentToken as string;

    const described = await describeIntent(token);
    expect(described.statusCode).toBe(200);
    expect(described.json().classroom.title).toBe(classroom.title);

    // Describing an intent is not joining: nothing is created by it.
    expect(described.cookies).toHaveLength(0);
    const memberships = await admin.query(
      `SELECT count(*)::int AS n FROM classroom_memberships WHERE classroom_id = $1`,
      [classroom.classroomId],
    );
    expect(memberships.rows[0].n).toBe(0);
  });

  it('cannot be forged, edited or replaced by a raw classroom identifier', async () => {
    const code = freshCode();
    const classroom = await seedClassroom('forge', code);
    const token = (await resolve(code)).json().classroom.joinIntentToken as string;

    // The raw identifier is not a credential for this endpoint.
    expect((await describeIntent(classroom.classroomId)).statusCode).toBe(410);
    // A tampered signature is refused.
    expect((await describeIntent(`${token}x`)).statusCode).toBe(410);
    // A tampered payload is refused.
    const [, signature] = token.split('.');
    const forgedPayload = Buffer.from(
      JSON.stringify({ c: classroom.classroomId, v: 1, e: Math.floor(Date.now() / 1000) + 600 }),
    ).toString('base64url');
    expect((await describeIntent(`${forgedPayload}.${signature}`)).statusCode).toBe(410);
    // Nonsense is refused with the same answer, revealing nothing.
    expect((await describeIntent('not-a-token')).statusCode).toBe(410);
  });

  it('stops working when the class code it came from is rotated', async () => {
    const code = freshCode();
    const classroom = await seedClassroom('intent-rotate', code);
    const token = (await resolve(code)).json().classroom.joinIntentToken as string;
    expect((await describeIntent(token)).statusCode).toBe(200);

    await admin.query(`SELECT classroom_issue_join_code($1, $2, $3)`, [
      classroom.tenantId,
      classroom.classroomId,
      digestOf(freshCode()),
    ]);

    expect((await describeIntent(token)).statusCode).toBe(410);
  });
});

describe('the class-code secret', () => {
  it('refuses to resolve or describe when the secret is missing', async () => {
    const code = freshCode();
    await seedClassroom('secret-missing', code);
    const token = (await resolve(code)).json().classroom.joinIntentToken as string;

    await withSecret(undefined, async () => {
      const resolved = await resolve(code);
      expect(resolved.statusCode).toBe(503);
      expect(resolved.json().error.code).toBe('join_codes_unavailable');

      const described = await describeIntent(token);
      expect(described.statusCode).toBe(503);
      expect(described.json().error.code).toBe('join_codes_unavailable');
    });
  });

  it('refuses a damaged secret instead of digesting with it', async () => {
    const code = freshCode();
    await seedClassroom('secret-damaged', code);

    // Too short to be a key: treated as absent, never as "good enough".
    await withSecret('short', async () => {
      const resolved = await resolve(code);
      expect(resolved.statusCode).toBe(503);
      expect(resolved.json().error.code).toBe('join_codes_unavailable');
    });
  });

  it('does not silently accept a different secret for existing codes', async () => {
    const code = freshCode();
    await seedClassroom('secret-rotated', code);

    // A replacement key cannot resolve a code digested with the old one; the
    // answer is an honest "not found", never a wrong class.
    await withSecret('a-different-but-well-formed-pepper-0123456789', async () => {
      expect((await resolve(code)).statusCode).toBe(404);
    });

    // With the real secret restored, the same code still works.
    expect((await resolve(code)).statusCode).toBe(200);
  });
});
