-- C1.1 owner-review blockers: identity integrity and a real class-code model.
--
-- Four corrections, all additive to the data that already exists:
--
--   1. class codes stop living in plain text on `classrooms`. They move to
--      their own versioned table that stores only a keyed digest, and the code
--      itself is generated by the application with a CSPRNG — never by SQL
--      random(), which is neither uniform for secrets nor unpredictable.
--   2. `principals` no longer accepts a row with no subject: until
--      `student_seats` exists there is nothing for a seat principal to point
--      at, so only account principals are allowed.
--   3. capabilities and profile visibility follow the normative sets from the
--      target blueprint (`registered_student`; private | restricted | public).
--   4. the legacy tenant-scoped user leaves `workspace_memberships` for its
--      own link table, so a membership means membership and nothing else.

-- ---------------------------------------------------------------------------
-- 1. Class codes: versioned, digest-only, rotatable.
-- ---------------------------------------------------------------------------
DROP TRIGGER IF EXISTS classrooms_set_join_code ON classrooms;
DROP FUNCTION IF EXISTS classroom_set_join_code();
DROP FUNCTION IF EXISTS classroom_generate_join_code();
DROP FUNCTION IF EXISTS classroom_resolve_join_code(varchar);
DROP INDEX IF EXISTS classrooms_join_code_idx;
ALTER TABLE classrooms DROP COLUMN IF EXISTS join_code;

/**
 * One row per issued class code.
 *
 * `lookup_digest` is a keyed digest (HMAC with a server-side pepper) of the
 * normalized code, so a database copy alone does not reveal a working code.
 * The code itself is returned exactly once, when it is generated or rotated;
 * it is never stored and cannot be read back.
 */
CREATE TABLE IF NOT EXISTS classroom_join_codes (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     uuid NOT NULL REFERENCES tenants(id),
    classroom_id  uuid NOT NULL,
    version       integer NOT NULL,
    lookup_digest text    NOT NULL,
    status        varchar(16) NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'revoked', 'expired')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    rotated_at    timestamptz,
    revoked_at    timestamptz,
    expires_at    timestamptz,
    FOREIGN KEY (tenant_id, classroom_id) REFERENCES classrooms (tenant_id, id),
    UNIQUE (classroom_id, version)
);
-- A digest resolves to at most one class, and only while it is active.
CREATE UNIQUE INDEX IF NOT EXISTS classroom_join_codes_digest_idx
    ON classroom_join_codes (lookup_digest) WHERE status = 'active';
CREATE UNIQUE INDEX IF NOT EXISTS classroom_join_codes_one_active_idx
    ON classroom_join_codes (classroom_id) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS classroom_join_codes_classroom_idx
    ON classroom_join_codes (tenant_id, classroom_id);

-- The runtime role reaches codes only through the functions below.
ALTER TABLE classroom_join_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE classroom_join_codes FORCE  ROW LEVEL SECURITY;
REVOKE ALL ON classroom_join_codes FROM asalab_app;

/**
 * Issue a code for a classroom: the previous active code is rotated out in the
 * same statement, so exactly one code is valid at a time.
 *
 * The caller supplies the digest of a code it generated with a CSPRNG. The
 * database never sees the code and never invents one.
 */
CREATE OR REPLACE FUNCTION classroom_issue_join_code(
    p_tenant_id uuid,
    p_classroom_id uuid,
    p_lookup_digest text
)
RETURNS TABLE (join_code_id uuid, version integer)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
DECLARE
    v_version integer;
    v_id      uuid;
BEGIN
    UPDATE public.classroom_join_codes
       SET status = 'revoked', rotated_at = now(), revoked_at = now()
     WHERE classroom_id = p_classroom_id AND status = 'active';

    SELECT COALESCE(max(c.version), 0) + 1 INTO v_version
      FROM public.classroom_join_codes c
     WHERE c.classroom_id = p_classroom_id;

    INSERT INTO public.classroom_join_codes (tenant_id, classroom_id, version, lookup_digest)
    VALUES (p_tenant_id, p_classroom_id, v_version, p_lookup_digest)
    RETURNING id INTO v_id;

    RETURN QUERY SELECT v_id, v_version;
END;
$$;

/** Revoke the active code of a classroom without issuing a new one. */
CREATE OR REPLACE FUNCTION classroom_revoke_join_code(p_tenant_id uuid, p_classroom_id uuid)
RETURNS integer
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
DECLARE
    v_count integer;
BEGIN
    UPDATE public.classroom_join_codes
       SET status = 'revoked', revoked_at = now()
     WHERE tenant_id = p_tenant_id AND classroom_id = p_classroom_id AND status = 'active';
    GET DIAGNOSTICS v_count = ROW_COUNT;
    RETURN v_count;
END;
$$;

/**
 * Resolve an active digest into a class preview.
 *
 * SECURITY DEFINER on purpose: the visitor has no tenant context yet, so
 * row-level security cannot answer for them. The function returns only what
 * the confirmation screen shows and grants nothing: no membership, no session
 * and no seat follow from it.
 */
CREATE OR REPLACE FUNCTION classroom_resolve_join_digest(p_lookup_digest text)
RETURNS TABLE (classroom_id uuid, title varchar, educator_display_name varchar)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
    SELECT c.id, c.title, u.display_name
      FROM public.classroom_join_codes j
      JOIN public.classrooms c ON c.tenant_id = j.tenant_id AND c.id = j.classroom_id
      JOIN public.users u ON u.tenant_id = c.tenant_id AND u.id = c.created_by
     WHERE j.lookup_digest = p_lookup_digest
       AND j.status = 'active'
       AND (j.expires_at IS NULL OR j.expires_at > now())
       AND c.status = 'active'
     LIMIT 1;
$$;

REVOKE ALL ON FUNCTION classroom_issue_join_code(uuid, uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION classroom_revoke_join_code(uuid, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION classroom_resolve_join_digest(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION classroom_issue_join_code(uuid, uuid, text) TO asalab_app;
GRANT EXECUTE ON FUNCTION classroom_revoke_join_code(uuid, uuid) TO asalab_app;
GRANT EXECUTE ON FUNCTION classroom_resolve_join_digest(text) TO asalab_app;

-- ---------------------------------------------------------------------------
-- 2. Principal integrity: no principal without a subject.
-- ---------------------------------------------------------------------------
-- A seat principal needs a `student_seats` row to point at, and that entity
-- does not exist yet. Allowing `kind = 'student_seat'` with no subject would
-- let an empty principal own content, so only account principals are valid
-- until the seat table and its foreign key arrive together.
DELETE FROM principals WHERE kind = 'student_seat' AND account_id IS NULL;
ALTER TABLE principals DROP CONSTRAINT IF EXISTS principals_exactly_one_subject;
ALTER TABLE principals ADD CONSTRAINT principals_account_subject_present
    CHECK (kind = 'account' AND account_id IS NOT NULL);

-- ---------------------------------------------------------------------------
-- 3. Normative capability and visibility sets (target blueprint).
-- ---------------------------------------------------------------------------
ALTER TABLE capability_grants DROP CONSTRAINT IF EXISTS capability_grants_capability_check;
ALTER TABLE capability_grants ADD CONSTRAINT capability_grants_capability_check
    CHECK (capability IN ('creator', 'educator', 'registered_student', 'guardian', 'platform_admin'));

-- Profile visibility is its own axis: `unlisted` belongs to project visibility
-- and never described a profile, so the existing value becomes `restricted`.
ALTER TABLE profiles RENAME COLUMN privacy TO visibility;
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_privacy_check;
UPDATE profiles SET visibility = 'restricted' WHERE visibility = 'unlisted';
ALTER TABLE profiles ALTER COLUMN visibility SET DEFAULT 'private';
ALTER TABLE profiles ADD CONSTRAINT profiles_visibility_check
    CHECK (visibility IN ('private', 'restricted', 'public'));

-- Workspace roles follow the normative set; the version is recorded so a later
-- extension is a deliberate migration rather than a silent widening.
ALTER TABLE workspace_memberships DROP CONSTRAINT IF EXISTS workspace_memberships_role_check;
ALTER TABLE workspace_memberships ADD CONSTRAINT workspace_memberships_role_check
    CHECK (role IN ('owner', 'member', 'educator', 'school_admin', 'billing_admin', 'moderator'));
COMMENT ON COLUMN workspace_memberships.role IS
    'Scoped workspace role, normative set of asa-target-platform-2026-07: owner, member, educator, school_admin, billing_admin, moderator.';

-- ---------------------------------------------------------------------------
-- 4. Legacy execution identity leaves membership.
-- ---------------------------------------------------------------------------
/**
 * The bridge between a global account and the tenant-scoped `users` row that
 * still executes its work.
 *
 * It carries the composite tenant integrity that a membership column could not:
 * (tenant_id, user_id) is a real foreign key into `users`. A personal workspace
 * has no row here at all, which is exactly the point — it does not depend on
 * `users` existing.
 */
CREATE TABLE IF NOT EXISTS legacy_user_account_links (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       uuid NOT NULL REFERENCES tenants(id),
    user_id         uuid NOT NULL,
    account_id      uuid NOT NULL REFERENCES accounts(id),
    principal_id    uuid NOT NULL REFERENCES principals(id),
    migration_state varchar(32) NOT NULL DEFAULT 'active'
                    CHECK (migration_state IN ('active', 'superseded', 'retired')),
    created_at      timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id),
    UNIQUE (tenant_id, user_id)
);
CREATE INDEX IF NOT EXISTS legacy_user_account_links_account_idx
    ON legacy_user_account_links (account_id);

ALTER TABLE legacy_user_account_links ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON legacy_user_account_links FROM asalab_app;

INSERT INTO legacy_user_account_links (tenant_id, user_id, account_id, principal_id)
SELECT w.tenant_id, m.user_id, m.account_id, p.id
  FROM workspace_memberships m
  JOIN workspaces w ON w.id = m.workspace_id
  JOIN principals p ON p.account_id = m.account_id
 WHERE m.user_id IS NOT NULL
   AND NOT EXISTS (
        SELECT 1 FROM legacy_user_account_links l
         WHERE l.tenant_id = w.tenant_id AND l.user_id = m.user_id);

ALTER TABLE workspace_memberships DROP COLUMN IF EXISTS user_id;

/** Account behind a legacy tenant-scoped session, through the link table. */
CREATE OR REPLACE FUNCTION auth_account_for_user(p_tenant_id uuid, p_user_id uuid)
RETURNS TABLE (account_id uuid)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
    SELECT l.account_id
      FROM public.legacy_user_account_links l
     WHERE l.tenant_id = p_tenant_id AND l.user_id = p_user_id AND l.migration_state = 'active'
     LIMIT 1;
$$;

/**
 * Workspaces the account may act in.
 *
 * `user_id` is the legacy execution identity for that workspace, read from the
 * link table; a personal workspace simply has none until principal-aware
 * sessions land.
 */
CREATE OR REPLACE FUNCTION auth_account_workspaces(p_account_id uuid)
RETURNS TABLE (
    workspace_id uuid,
    tenant_id uuid,
    kind varchar,
    title varchar,
    role varchar,
    user_id uuid
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
    SELECT w.id, w.tenant_id, w.kind, w.title, m.role, l.user_id
      FROM public.workspace_memberships m
      JOIN public.workspaces w ON w.id = m.workspace_id
      LEFT JOIN public.legacy_user_account_links l
             ON l.tenant_id = w.tenant_id
            AND l.account_id = m.account_id
            AND l.migration_state = 'active'
     WHERE m.account_id = p_account_id
     ORDER BY (w.kind = 'personal') DESC, w.title;
$$;

/**
 * Register an adult account with its Personal Workspace.
 *
 * Unchanged in intent from 0005; the membership simply no longer carries a
 * legacy user column. A Personal Workspace is still not a school: no
 * `schools`, no `academic_periods`, no `users` row is created.
 */
CREATE OR REPLACE FUNCTION auth_register_account(
    p_email          varchar,
    p_password_hash  text,
    p_display_name   varchar,
    p_username       varchar,
    p_birth_date     date,
    p_country        varchar,
    p_policy_version varchar
)
RETURNS TABLE (account_id uuid, workspace_id uuid, tenant_id uuid)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, pg_temp AS $$
DECLARE
    v_account   uuid;
    v_tenant    uuid;
    v_workspace uuid;
    v_slug      varchar(64);
BEGIN
    INSERT INTO public.accounts (email, password_hash, birth_date, country)
    VALUES (lower(p_email), p_password_hash, p_birth_date, upper(p_country))
    RETURNING id INTO v_account;

    INSERT INTO public.profiles (account_id, username, display_name)
    VALUES (v_account, p_username, COALESCE(NULLIF(p_display_name, ''), p_username));

    INSERT INTO public.principals (kind, account_id) VALUES ('account', v_account);

    INSERT INTO public.capability_grants (account_id, capability, state, policy_version, granted_by)
    VALUES (v_account, 'creator', 'verified', p_policy_version, 'server');

    v_slug := 'personal-' || pg_catalog.replace(v_account::text, '-', '');
    INSERT INTO public.tenants (workspace_slug, title)
    VALUES (v_slug, COALESCE(NULLIF(p_display_name, ''), p_username))
    RETURNING id INTO v_tenant;
    INSERT INTO public.tenant_placements (tenant_id, mode) VALUES (v_tenant, 'SHARED_CLUSTER');

    INSERT INTO public.workspaces (tenant_id, kind, title)
    VALUES (v_tenant, 'personal', COALESCE(NULLIF(p_display_name, ''), p_username))
    RETURNING id INTO v_workspace;

    INSERT INTO public.workspace_memberships (account_id, workspace_id, role)
    VALUES (v_account, v_workspace, 'owner');

    -- actor_user_id stays NULL: the actor is an account principal, and the
    -- composite foreign key is not enforced when the column is NULL.
    INSERT INTO public.audit_events (tenant_id, actor_user_id, entity_type, entity_id, action, payload_json)
    VALUES (v_tenant, NULL, 'account', v_account, 'account.registered',
            pg_catalog.jsonb_build_object('workspaceKind', 'personal', 'policyVersion', p_policy_version));

    RETURN QUERY SELECT v_account, v_workspace, v_tenant;
END;
$$;
