export {
  EMPTY_DOCUMENT,
  DEFAULT_SIMULATION,
  DEFAULT_VIEWPORT,
  parseElectronicsDocument,
  terminalsForKind,
  type ComponentKind,
  type DocumentParseResult,
  type ElectronicsDocument,
  type ElectronicsViewport,
  type ProductionStateValue,
  type Rotation,
  type SchematicComponent,
  type SchematicConnection,
  type SimulationSettings,
  type Terminal,
  type TerminalRef,
} from './domain/document.js';
export type { ElectronicsDocument as SchematicDocument } from './domain/document.js';
export { buildNetlist, terminalKey, type Netlist } from './domain/netlist.js';
export {
  canonicalSimulationInput,
  sha256Hex,
  simulationInputDigest,
  SIMULATION_INPUT_DIGEST_VERSION,
} from './domain/simulation-input-digest.js';
export {
  ledBrightnessPercent,
  ledForwardVoltageAtCurrent,
  ordinaryLedProfile,
  rgbLedProfile,
  ORDINARY_LED_PROFILES,
  RGB_LED_PROFILES,
  SEVEN_SEGMENT_COMMON_TERMINALS,
  SEVEN_SEGMENT_LED_PROFILE,
  SEVEN_SEGMENT_TERMINALS,
  type LedJunctionProfile,
  type OrdinaryLedColour,
  type RgbLedChannel,
  type SevenSegmentId,
} from './domain/led-model.js';
export {
  canonicalElectricalModelRegistry,
  componentModelIdentityIsInstalled,
  electricalModelIdentityForComponent,
  electricalModelRegistryEntries,
  isKnownElectricalModelId,
  resolveElectricalModelIdentity,
  ELECTRICAL_MODEL_REGISTRY_VERSION,
  type ElectricalModelIdentity,
  type ElectricalModelRegistryEntry,
} from './domain/model-identity.js';
export {
  electricalModelFor,
  unsupportedElectricalComponents,
  validateElectricalTerminalContract,
  type ElectricalModelDescriptor,
  type ElectricalModelId,
  type ElectricalModelSupport,
  type ElectricalTerminalContractResult,
} from './domain/model-registry.js';
export type {
  DcStampContext,
  DeviceModel,
  IterativeDcDeviceModel,
  IterativeDcStampContext,
  ModelIssue,
  NormalizedDevice,
} from './domain/models/device-model.js';
export {
  BRUSHED_MOTOR_ASSEMBLY_PROFILES,
  BRUSHED_MOTOR_PROFILE_REGISTRY_VERSION,
  BRUSHED_MOTOR_PROFILE_SOURCES,
  DEFAULT_BRUSHED_MOTOR_PROFILE_IDS,
  MOTOR_ASSEMBLY_PROFILE_PROPERTY,
  brushedMotorProfile,
  brushedMotorProfilesForComponent,
  canonicalBrushedMotorProfileRegistry,
  canonicalBrushedMotorReferenceFixtures,
  resolveBrushedMotorProfileSelection,
  validateBrushedMotorProfileRegistry,
  type BrushedMotorAssemblyProfile,
  type MotorComponentTypeId,
  type MotorNumericParameter,
  type MotorParameterBasis,
  type MotorProfileSelection,
  type MotorProfileSelectionError,
  type MotorProfileSource,
  type MotorReferencePoint,
  type MotorTransmissionProfile,
} from './domain/models/brushed-motor-profiles.js';
export {
  BRUSHED_MOTOR_AMBIENT_TEMPERATURE_CELSIUS,
  BRUSHED_MOTOR_DAMAGE_EXPOSURE_SECONDS,
  BRUSHED_MOTOR_TRANSIENT_MODEL_VERSION,
  advanceBrushedMotorTransientState,
  brushedMotorCompanion,
  brushedMotorTransientStateIsCompatible,
  createBrushedMotorTransientState,
  createBrushedMotorTransientStateForComponent,
  observeBrushedMotorTransientState,
  type BrushedMotorCompanion,
  type BrushedMotorDirection,
  type BrushedMotorFailureMode,
  type BrushedMotorInitialStateResult,
  type BrushedMotorObservation,
  type BrushedMotorOperatingMode,
  type BrushedMotorStepInput,
  type BrushedMotorStepResult,
  type BrushedMotorThermalState,
  type BrushedMotorTransientStateEntry,
} from './domain/models/brushed-motor-transient-model.js';
export {
  createLinearDcDevice,
  isResistorDevice,
  isMultimeterDcVoltageDevice,
  isSourceDevice,
  MULTIMETER_DC_INPUT_RESISTANCE_OHM,
  MULTIMETER_DC_MAX_INPUT_VOLTAGE,
  MULTIMETER_DC_VOLTAGE_DEVICE_MODEL,
  resistorPowerRatingWatt,
  sourceContinuousCurrentAmp,
  RESISTOR_DEVICE_MODEL,
  SOURCE_DEVICE_MODEL,
  type LinearDcDevice,
  type ResistorParameters,
  type SourceParameters,
  type MultimeterDcVoltageParameters,
  type MultimeterDcVoltageDevice,
} from './domain/models/linear-dc-models.js';
export {
  advanceIncandescentLampThermalState,
  canonicalIncandescentLampProfileRegistry,
  incandescentLampBrightnessPercent,
  incandescentLampFilamentState,
  incandescentLampResistanceOhm,
  INCANDESCENT_LAMP_PROFILE,
  type IncandescentLampFilamentState,
  type IncandescentLampThermalObservation,
} from './domain/models/incandescent-lamp-model.js';
export {
  canonicalNpnDcProfileRegistry,
  classifyNpnOperatingRegion,
  createNpnDcDevice,
  NPN_DC_PROFILES,
  NPN_DEVICE_MODEL,
  type NpnDcDevice,
  type NpnIterationState,
  type NpnObservation,
  type NpnOperatingPoint,
  type NpnOperatingRegion,
  type NpnParameters,
  type NpnProfile,
  type NpnStressState,
} from './domain/models/npn-dc-model.js';
export {
  canonicalPhotoresistorProfileRegistry,
  photoresistorIllumination,
  photoresistorIlluminanceLux,
  photoresistorResistanceAtIlluminanceOhm,
  photoresistorResistanceOhm,
  PHOTORESISTOR_BRIGHT_RESISTANCE_OHM,
  PHOTORESISTOR_DARK_RESISTANCE_OHM,
  PHOTORESISTOR_DEFAULT_ILLUMINATION,
  PHOTORESISTOR_PROFILE,
  PHOTORESISTOR_PROFILE_REGISTRY_VERSION,
} from './domain/photoresistor-model.js';
export {
  buttonContactPairs,
  spdtConnections,
  spdtSelectedTerminal,
  spdtStateForThrow,
  spdtThrowFromState,
  SPDT_TERMINALS,
  TACTILE_BUTTON_TERMINALS,
  type SpdtThrow,
} from './domain/switch-topology.js';
export {
  solveCircuit,
  sourceInternalResistanceOhm,
  type ComponentResult,
  type DamageState,
  type Diagnostic,
  type DiagnosticAnchor,
  type DiagnosticCode,
  type DiagnosticSeverity,
  type DeviceHealth,
  type NodeResult,
  type PresentationState,
  type SimulationSolveStatus,
  type SolveResult,
} from './domain/solver.js';
export type {
  CapacitorTransientState,
  CapacitorTransientStateEntry,
  ThermalTransientStateEntry,
  TransientFailureMode,
} from './domain/models/capacitor-transient-model.js';
export {
  analyseCircuit,
  compileCircuit,
  type CompiledCircuit,
  type CompiledNet,
  type SimulationQuality,
  type SimulationResult,
  type SimulationOptions,
  type SimulationStatus,
} from './domain/simulation.js';
export { ELECTRONICS_MODULE } from './module.js';
