export {
  BREADBOARD_CENTER_GAP_MM,
  BREADBOARD_HOLE_PITCH_MM,
  areBreadboardHolesConnected,
  breadboardBusMembers,
  breadboardEnvelopeMm,
  breadboardHole,
  breadboardHoleWorldMm,
  breadboardInternalBusMap,
  createBreadboardDefinition,
  expectedBreadboardTiePointCount,
  nearestBreadboardHole,
  rotateBreadboardPointMm,
  type BreadboardDefinition,
  type BreadboardEvidence,
  type BreadboardHole,
  type BreadboardHoleRegion,
  type BreadboardKind,
  type BreadboardPlacementMm,
  type BreadboardPointMm,
  type BreadboardRailId,
  type BreadboardRotation,
  type BreadboardTerminalRow,
  type NearestBreadboardHole,
} from './domain/breadboard.js';
export {
  breadboardInternalLinks,
  breadboardTerminalIds,
  type BreadboardInternalLink,
} from './domain/breadboard-netlist.js';
export {
  COMPONENT_KINDS,
  COMPONENT_TERMINAL_MODELS,
  COMPONENT_VALUE_MODELS,
  componentTerminalIds,
  componentTerminalModel,
  componentTerminalModels,
  componentValueError,
  isComponentTerminal,
  isNominalComponentValue,
  type ComponentKind,
  type ComponentTerminalModel,
  type ComponentValueModel,
  type TerminalElectricalRole,
  type TerminalId,
} from './domain/component-model.js';
export {
  EMPTY_DOCUMENT,
  parseElectronicsDocument,
  type ComponentPosition,
  type DocumentParseResult,
  type ElectronicsDocument,
  type ElectronicsGeometryProfile,
  type SchematicComponent,
  type SchematicConnection,
  type SchematicEndpoint,
  type Terminal,
} from './domain/document.js';
export {
  buildNetlist,
  buildNetlistFromTerminalMap,
  terminalKey,
  type Netlist,
  type TerminalRef,
} from './domain/netlist.js';
export {
  solveCircuit,
  type ComponentResult,
  type Diagnostic,
  type DiagnosticCode,
  type DiagnosticSeverity,
  type SolveResult,
} from './domain/solver.js';
