export {
  BREADBOARD_CENTER_GAP_MM,
  BREADBOARD_HOLE_PITCH_MM,
  areBreadboardHolesConnected,
  breadboardBusMembers,
  breadboardEnvelopeMm,
  breadboardHole,
  breadboardHoleWorldMm,
  breadboardInternalBusMap,
  createBreadboardDefinition,
  expectedBreadboardTiePointCount,
  nearestBreadboardHole,
  rotateBreadboardPointMm,
  type BreadboardDefinition,
  type BreadboardEvidence,
  type BreadboardHole,
  type BreadboardHoleRegion,
  type BreadboardKind,
  type BreadboardPlacementMm,
  type BreadboardPointMm,
  type BreadboardRailId,
  type BreadboardRotation,
  type BreadboardTerminalRow,
  type NearestBreadboardHole,
} from './domain/breadboard.js';
export {
  breadboardInternalLinks,
  breadboardTerminalIds,
  type BreadboardInternalLink,
} from './domain/breadboard-netlist.js';
export {
  occupancyFromAssignments,
  planPartMountToBreadboard,
  type BreadboardHoleOccupant,
  type BreadboardMountFailure,
  type BreadboardMountPlan,
  type BreadboardOccupancy,
  type PlannedBreadboardMount,
  type PlanBreadboardMountOptions,
} from './domain/breadboard-mount-planner.js';
export {
  partTerminalWorldMm,
  snapPartToBreadboard,
  type BreadboardPartSnapFailure,
  type BreadboardPartSnapResult,
  type BreadboardPartSnapSuccess,
  type BreadboardTerminalAssignment,
  type PhysicalPartDefinitionMm,
  type PhysicalPartPlacementMm,
  type PhysicalPartTerminalMm,
} from './domain/breadboard-placement.js';
export {
  COMPONENT_KINDS,
  COMPONENT_TERMINAL_MODELS,
  COMPONENT_VALUE_MODELS,
  componentTerminalIds,
  componentTerminalModel,
  componentTerminalModels,
  componentValueError,
  isComponentTerminal,
  isNominalComponentValue,
  type ComponentKind,
  type ComponentTerminalModel,
  type ComponentValueModel,
  type TerminalElectricalRole,
  type TerminalId,
} from './domain/component-model.js';
export {
  COMPONENT_PROPERTY_SCHEMAS,
  defaultComponentProperties,
  legacyValueToComponentProperties,
  validateComponentProperties,
  type BooleanPropertyDefinition,
  type ComponentPropertyDefinition,
  type ComponentPropertyPrimitive,
  type ComponentPropertySchema,
  type ComponentPropertyValidation,
  type ComponentPropertyValidationFailure,
  type ComponentPropertyValidationSuccess,
  type ComponentPropertyValue,
  type EnumPropertyDefinition,
  type NumberPropertyDefinition,
} from './domain/component-properties.js';
export {
  ACTIVE_NATIVE_COMPONENT_GEOMETRY,
  NATIVE_GEOMETRY_EPSILON_MM,
  NATIVE_GRID_PITCH_MM,
  calibratedAssetSizeMm,
  createAxialResistorGeometry,
  rotateNativePoint,
  rotatedEnvelopeMm,
  terminalDistanceMm,
  validateNativeComponentGeometry,
  type NativeAssetCalibration,
  type NativeComponentGeometry,
  type NativeGeometryEvidence,
  type NativeGeometryValidation,
  type NativeMountingMode,
  type NativePointMm,
  type NativeSizeMm,
  type NativeTerminalGeometry,
  type QuarterTurn,
} from './domain/native-component-geometry.js';
export {
  resistorBandCssColors,
  resistorFourBandCode,
  type FourBandResistorCode,
  type ResistorBandColor,
  type ResistorBandDefinition,
} from './domain/resistor-color-code.js';
export {
  EMPTY_DOCUMENT,
  parseElectronicsDocument,
  type ComponentPosition,
  type DocumentParseResult,
  type ElectronicsDocument,
  type ElectronicsGeometryProfile,
  type SchematicComponent,
  type SchematicConnection,
  type SchematicEndpoint,
  type Terminal,
} from './domain/document.js';
export {
  buildNetlist,
  buildNetlistFromTerminalMap,
  terminalKey,
  type Netlist,
  type TerminalRef,
} from './domain/netlist.js';
export {
  solveCircuit,
  type ComponentResult,
  type Diagnostic,
  type DiagnosticCode,
  type DiagnosticSeverity,
  type SolveResult,
} from './domain/solver.js';
