export type {
  ComponentKind,
  ElectronicsDocument,
  ElectronicsViewport,
  Rotation,
  SchematicComponent,
  SchematicConnection,
  SimulationSettings,
  Terminal,
  TerminalRef,
} from './domain/document.js';
export { buildNetlist, terminalKey, type Netlist } from './domain/netlist.js';
export {
  canonicalElectricalModelRegistry,
  componentModelIdentityIsInstalled,
  electricalModelIdentityForComponent,
  electricalModelRegistryEntries,
  isKnownElectricalModelId,
  resolveElectricalModelIdentity,
  ELECTRICAL_MODEL_REGISTRY_VERSION,
  type ElectricalModelIdentity,
  type ElectricalModelRegistryEntry,
} from './domain/model-identity.js';
export {
  canonicalSimulationInput,
  sha256Hex,
  simulationInputDigest,
  SIMULATION_INPUT_DIGEST_VERSION,
} from './domain/simulation-input-digest.js';
export {
  analyseCircuit,
  compileCircuit,
  type CompiledCircuit,
  type CompiledNet,
  type SimulationQuality,
  type SimulationResult,
  type SimulationOptions,
  type SimulationStatus,
} from './domain/simulation.js';
export type {
  CapacitorTransientState,
  CapacitorTransientStateEntry,
  ThermalTransientStateEntry,
  TransientFailureMode,
} from './domain/models/capacitor-transient-model.js';
export {
  BRUSHED_MOTOR_ASSEMBLY_PROFILES,
  BRUSHED_MOTOR_PROFILE_REGISTRY_VERSION,
  BRUSHED_MOTOR_PROFILE_SOURCES,
  DEFAULT_BRUSHED_MOTOR_PROFILE_IDS,
  MOTOR_ASSEMBLY_PROFILE_PROPERTY,
  brushedMotorProfile,
  brushedMotorProfilesForComponent,
  canonicalBrushedMotorProfileRegistry,
  canonicalBrushedMotorReferenceFixtures,
  resolveBrushedMotorProfileSelection,
  validateBrushedMotorProfileRegistry,
  type BrushedMotorAssemblyProfile,
  type MotorComponentTypeId,
  type MotorNumericParameter,
  type MotorParameterBasis,
  type MotorProfileSelection,
  type MotorProfileSelectionError,
  type MotorProfileSource,
  type MotorReferencePoint,
  type MotorTransmissionProfile,
} from './domain/models/brushed-motor-profiles.js';
export {
  BRUSHED_MOTOR_AMBIENT_TEMPERATURE_CELSIUS,
  BRUSHED_MOTOR_DAMAGE_EXPOSURE_SECONDS,
  BRUSHED_MOTOR_TRANSIENT_MODEL_VERSION,
  advanceBrushedMotorTransientState,
  brushedMotorCompanion,
  brushedMotorTransientStateIsCompatible,
  createBrushedMotorTransientState,
  createBrushedMotorTransientStateForComponent,
  observeBrushedMotorTransientState,
  type BrushedMotorCompanion,
  type BrushedMotorDirection,
  type BrushedMotorFailureMode,
  type BrushedMotorInitialStateResult,
  type BrushedMotorObservation,
  type BrushedMotorOperatingMode,
  type BrushedMotorStepInput,
  type BrushedMotorStepResult,
  type BrushedMotorThermalState,
  type BrushedMotorTransientStateEntry,
} from './domain/models/brushed-motor-transient-model.js';
export type {
  ComponentResult,
  Diagnostic,
  DiagnosticAnchor,
  DiagnosticCode,
  DiagnosticSeverity,
  NodeResult,
  SimulationSolveStatus,
  SolveResult,
} from './domain/solver.js';
